# Generated by Django 2.0.1 on 2019-04-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_permission_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='roles',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
